### PR TITLE
we can now load a new video (no server sync implemented yet)

### PR DESCRIPTION
**Pull request by ShuoShen**

### CODE REVIEW

**Comment by ShuoShen** [comment]
- able to change video id on the client side
- updated react version to 0.13 (for DOM support)

**Comment by ShuoShen** [comment]
居然没有nit?

**Comment by jeffyuans** [comment]
给不给力

On Monday, April 13, 2015, Shuo Shen notifications@github.com wrote:

> 居然没有nit?
> 
> On Mon, Apr 13, 2015 at 6:12 PM, Shuai <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Merged #3 https://github.com/ShuaiYuan87/FlyOtter/pull/3.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ShuaiYuan87/FlyOtter/pull/3#event-280349132.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ShuaiYuan87/FlyOtter/pull/3#issuecomment-92555332.

## 

Thanks,
Shuai

**Comment by ShuoShen** [comment]
极佳

http://techcrunch.com/2015/04/12/this-stream-aint-big-enough-for-the-both-of-us/#.vserga:7yq7

**Pull request merged**
